package com.edutrack.presentation.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.edutrack.Res
import com.edutrack.montserrat_bold
import com.edutrack.montserrat_medium
import com.edutrack.montserrat_regular
import org.jetbrains.compose.resources.Font

// ─────────────────────────────────────────────
//  Color Palette — EduTrack
//  Seed: #FFD3AE
//  Generated by Mismaiti · DO NOT EDIT
// ─────────────────────────────────────────────

object EduTrackColors {

    // Brand
    val primary = Color(0xFFFAC89E)
    val secondary = Color(0xFFE3D6B5)
    val tertiary = Color(0xFFCFECAC)

    // Semantic
    val success = Color(0xFF22D98A)
    val warning = Color(0xFFFFB74D)
    val error = Color(0xFFEF5350)

    // Gradient helpers
    val primaryGradient = listOf(primary, secondary)
    val heroGradient = listOf(primary.copy(alpha = 0.8f), secondary.copy(alpha = 0.6f))
}

// ─────────────────────────────────────────────
//  Dark scheme
// ─────────────────────────────────────────────

val DarkColorScheme = darkColorScheme(
    primary = Color(0xFFFAC89E),
    onPrimary = Color(0xFF612F05),
    primaryContainer = Color(0xFF944605),
    onPrimaryContainer = Color(0xFFFCE4CF),
    secondary = Color(0xFFE3D6B5),
    onSecondary = Color(0xFF4A3D1C),
    secondaryContainer = Color(0xFF705B29),
    onSecondaryContainer = Color(0xFFF1EADA),
    tertiary = Color(0xFFCFECAC),
    onTertiary = Color(0xFF365313),
    tertiaryContainer = Color(0xFF517F1A),
    onTertiaryContainer = Color(0xFFE7F5D6),
    error = Color(0xFFF3A5A5),
    onError = Color(0xFF5A0C0C),
    errorContainer = Color(0xFF8A0F0F),
    onErrorContainer = Color(0xFFF9D2D2),
    surface = Color(0xFF100F0E),
    onSurface = Color(0xFFE7E5E4),
    surfaceVariant = Color(0xFF574C42),
    onSurfaceVariant = Color(0xFFD3CBC5),
    surfaceContainer = Color(0xFF211E1C),
    surfaceContainerLow = Color(0xFF1B1918),
    surfaceContainerHigh = Color(0xFF2E2B28),
    surfaceContainerHighest = Color(0xFF3C3834),
    surfaceDim = Color(0xFF100F0E),
    surfaceBright = Color(0xFF423D39),
    outline = Color(0xFFA8988A),
    outlineVariant = Color(0xFF574C42),
    inverseSurface = Color(0xFFE7E5E4),
    inverseOnSurface = Color(0xFF37332F),
    inversePrimary = Color(0xFFC95D03),
    scrim = Color(0xFF000000),
)

// ─────────────────────────────────────────────
//  Light scheme
// ─────────────────────────────────────────────

val LightColorScheme = lightColorScheme(
    primary = Color(0xFFC95D03),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFCE4CF),
    onPrimaryContainer = Color(0xFF301803),
    secondary = Color(0xFF977A35),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF1EADA),
    onSecondaryContainer = Color(0xFF251E0E),
    tertiary = Color(0xFF6CAB21),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFE7F5D6),
    onTertiaryContainer = Color(0xFF1B290A),
    error = Color(0xFFBA1212),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9D2D2),
    onErrorContainer = Color(0xFF2D0606),
    surface = Color(0xFFFAFAFA),
    onSurface = Color(0xFF1B1918),
    surfaceVariant = Color(0xFFE9E5E2),
    onSurfaceVariant = Color(0xFF574C42),
    surfaceContainer = Color(0xFFF1F0EF),
    surfaceContainerLow = Color(0xFFF6F5F4),
    surfaceContainerHigh = Color(0xFFECEAE9),
    surfaceContainerHighest = Color(0xFFE7E5E4),
    surfaceDim = Color(0xFFE0DEDB),
    surfaceBright = Color(0xFFFAFAFA),
    outline = Color(0xFF937E6C),
    outlineVariant = Color(0xFFD3CBC5),
    inverseSurface = Color(0xFF37332F),
    inverseOnSurface = Color(0xFFF3F2F1),
    inversePrimary = Color(0xFFFAC89E),
    scrim = Color(0xFF000000),
)

// ─────────────────────────────────────────────
//  Typography — bold-first scale (edgy)
// ─────────────────────────────────────────────

val LocalThemeIsDark = compositionLocalOf { mutableStateOf(true) }

@Composable
internal fun AppTheme(
    content: @Composable () -> Unit
) {
    val appFont = FontFamily(
        Font(resource = Res.font.montserrat_regular, weight = FontWeight.Normal),
        Font(resource = Res.font.montserrat_bold, weight = FontWeight.Bold),
        Font(resource = Res.font.montserrat_medium, weight = FontWeight.Medium),
    )

    val typography = Typography(
        displayLarge = TextStyle(fontFamily = appFont, fontWeight = FontWeight.Black, fontSize = 52.sp, letterSpacing = (-0.02).sp),
        displayMedium = TextStyle(fontFamily = appFont, fontWeight = FontWeight.ExtraBold, fontSize = 40.sp, letterSpacing = (-0.02).sp),
        displaySmall = TextStyle(fontFamily = appFont, fontWeight = FontWeight.ExtraBold, fontSize = 32.sp, letterSpacing = (-0.01).sp),
        headlineLarge = TextStyle(fontFamily = appFont, fontWeight = FontWeight.ExtraBold, fontSize = 28.sp, letterSpacing = (-0.01).sp),
        headlineMedium = TextStyle(fontFamily = appFont, fontWeight = FontWeight.Bold, fontSize = 22.sp),
        headlineSmall = TextStyle(fontFamily = appFont, fontWeight = FontWeight.Bold, fontSize = 18.sp),
        titleLarge = TextStyle(fontFamily = appFont, fontWeight = FontWeight.SemiBold, fontSize = 16.sp),
        titleMedium = TextStyle(fontFamily = appFont, fontWeight = FontWeight.SemiBold, fontSize = 14.sp),
        titleSmall = TextStyle(fontFamily = appFont, fontWeight = FontWeight.SemiBold, fontSize = 12.sp),
        bodyLarge = TextStyle(fontFamily = appFont, fontWeight = FontWeight.Normal, fontSize = 15.sp, lineHeight = 24.sp),
        bodyMedium = TextStyle(fontFamily = appFont, fontWeight = FontWeight.Normal, fontSize = 13.sp, lineHeight = 20.sp),
        bodySmall = TextStyle(fontFamily = appFont, fontWeight = FontWeight.Normal, fontSize = 11.sp, lineHeight = 16.sp),
        labelLarge = TextStyle(fontFamily = appFont, fontWeight = FontWeight.SemiBold, fontSize = 12.sp, letterSpacing = 0.04.sp),
        labelMedium = TextStyle(fontFamily = appFont, fontWeight = FontWeight.SemiBold, fontSize = 10.sp, letterSpacing = 0.06.sp),
        labelSmall = TextStyle(fontFamily = appFont, fontWeight = FontWeight.Bold, fontSize = 9.sp, letterSpacing = 0.08.sp),
    )

    // ─── Shapes — larger corner radii (edgy) ───
    val shapes = Shapes(
        extraSmall = RoundedCornerShape(6.dp),
        small = RoundedCornerShape(10.dp),
        medium = RoundedCornerShape(14.dp),
        large = RoundedCornerShape(20.dp),
        extraLarge = RoundedCornerShape(28.dp),
    )

    val systemIsDark = isSystemInDarkTheme()
    val isDarkState = remember(systemIsDark) { mutableStateOf(systemIsDark) }
    CompositionLocalProvider(
        LocalThemeIsDark provides isDarkState
    ) {
        val isDark by isDarkState
        SystemAppearance(!isDark)

        val colorScheme = if (isDark) DarkColorScheme else LightColorScheme

        MaterialTheme(
            colorScheme = colorScheme,
            typography = typography,
            shapes = shapes,
        ) {
            Surface(content = content)
        }
    }
}

@Composable
internal expect fun SystemAppearance(isDark: Boolean)

// ─────────────────────────────────────────────
//  Gradient utility — reads from current theme
// ─────────────────────────────────────────────

@Composable
fun primaryGradientBrush(): Brush = Brush.linearGradient(
    colors = listOf(
        MaterialTheme.colorScheme.primary,
        MaterialTheme.colorScheme.secondary,
    ),
    start = Offset.Zero,
    end = Offset.Infinite,
)
